query allEvents {
  allEvent {
    _id
    title
    startDate, 
    endDate, 
    url, 
    bgColor,
    mergedTitle,
    image {
      asset {
        _id
        assetId
      }
    }
    project {
      title,
      bgColor,
     	image {
      	asset {
          _id
          assetId
      	}
      }
    }
  }
}
