import { cookies } from "next/headers";

import "./globals.css";
import { Theme, ThemeProvider } from "../components/ThemeMode";
import { ThemeCookieKey } from "../utils/constants";
import "@fontsource-variable/montserrat";
import "@fontsource-variable/noto-sans-jp";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const getCookieThemeValue = () => {
  const cookie = cookies().get(ThemeCookieKey);
  if (cookie) {
    return cookie?.value as (typeof Theme)[keyof typeof Theme];
  }
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const themeValue = getCookieThemeValue();
  return (
    <ThemeProvider initialTheme={themeValue}>
      <html lang="es">
        <body>{children}</body>
      </html>
    </ThemeProvider>
  );
}

export const runtime = "edge";
